export const USER = {
  SIGN_UP: "SIGN_UP",
  UPDATE: "UPDATE",
};
export const AUTH = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT: "USERS_LOGOUT",
};
export const MUTUAL_FUND_PLAN = {
  FETCH_REQUEST: "FETCH_REQUEST",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_FAIL: "FETCH_FAIL",
  FILTER: "FILTER",
};
