export const USER = {
  SIGN_IN: "SIGN_IN",
  SIGN_UP: "SIGN_UP",
  UPDATE: "UPDATE",
};
export const AUTH = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "USERS_LOGOUT",
};
